apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notify-service
  description: Centralized multi-channel notification service
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: <your-org>/<your-repo>
spec:
  type: service
  owner: notify-team
  lifecycle: experimental
